name: Publish to NPM

permissions:
  id-token: write # Required for OIDC
  contents: read

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci npm ci --ignore-scripts
      - run: npm run build
      - run: npm publish
